# CMake generated Testfile for 
# Source directory: C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cat/test
# Build directory: C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cat/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(bsdcat_test_0 "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcat_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcat.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cat/test" "test_0")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(bsdcat_test_0 "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcat_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcat.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cat/test" "test_0")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(bsdcat_test_0 "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcat_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcat.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cat/test" "test_0")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(bsdcat_test_0 "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcat_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcat.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cat/test" "test_0")
else()
  add_test(bsdcat_test_0 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(bsdcat_test_empty_gz "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcat_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcat.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cat/test" "test_empty_gz")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(bsdcat_test_empty_gz "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcat_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcat.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cat/test" "test_empty_gz")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(bsdcat_test_empty_gz "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcat_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcat.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cat/test" "test_empty_gz")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(bsdcat_test_empty_gz "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcat_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcat.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cat/test" "test_empty_gz")
else()
  add_test(bsdcat_test_empty_gz NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(bsdcat_test_empty_lz4 "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcat_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcat.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cat/test" "test_empty_lz4")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(bsdcat_test_empty_lz4 "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcat_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcat.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cat/test" "test_empty_lz4")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(bsdcat_test_empty_lz4 "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcat_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcat.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cat/test" "test_empty_lz4")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(bsdcat_test_empty_lz4 "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcat_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcat.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cat/test" "test_empty_lz4")
else()
  add_test(bsdcat_test_empty_lz4 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(bsdcat_test_empty_xz "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcat_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcat.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cat/test" "test_empty_xz")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(bsdcat_test_empty_xz "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcat_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcat.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cat/test" "test_empty_xz")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(bsdcat_test_empty_xz "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcat_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcat.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cat/test" "test_empty_xz")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(bsdcat_test_empty_xz "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcat_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcat.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cat/test" "test_empty_xz")
else()
  add_test(bsdcat_test_empty_xz NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(bsdcat_test_empty_zstd "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcat_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcat.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cat/test" "test_empty_zstd")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(bsdcat_test_empty_zstd "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcat_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcat.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cat/test" "test_empty_zstd")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(bsdcat_test_empty_zstd "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcat_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcat.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cat/test" "test_empty_zstd")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(bsdcat_test_empty_zstd "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcat_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcat.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cat/test" "test_empty_zstd")
else()
  add_test(bsdcat_test_empty_zstd NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(bsdcat_test_error "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcat_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcat.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cat/test" "test_error")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(bsdcat_test_error "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcat_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcat.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cat/test" "test_error")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(bsdcat_test_error "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcat_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcat.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cat/test" "test_error")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(bsdcat_test_error "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcat_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcat.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cat/test" "test_error")
else()
  add_test(bsdcat_test_error NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(bsdcat_test_error_mixed "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcat_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcat.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cat/test" "test_error_mixed")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(bsdcat_test_error_mixed "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcat_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcat.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cat/test" "test_error_mixed")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(bsdcat_test_error_mixed "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcat_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcat.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cat/test" "test_error_mixed")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(bsdcat_test_error_mixed "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcat_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcat.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cat/test" "test_error_mixed")
else()
  add_test(bsdcat_test_error_mixed NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(bsdcat_test_expand_Z "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcat_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcat.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cat/test" "test_expand_Z")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(bsdcat_test_expand_Z "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcat_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcat.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cat/test" "test_expand_Z")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(bsdcat_test_expand_Z "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcat_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcat.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cat/test" "test_expand_Z")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(bsdcat_test_expand_Z "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcat_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcat.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cat/test" "test_expand_Z")
else()
  add_test(bsdcat_test_expand_Z NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(bsdcat_test_expand_bz2 "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcat_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcat.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cat/test" "test_expand_bz2")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(bsdcat_test_expand_bz2 "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcat_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcat.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cat/test" "test_expand_bz2")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(bsdcat_test_expand_bz2 "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcat_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcat.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cat/test" "test_expand_bz2")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(bsdcat_test_expand_bz2 "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcat_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcat.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cat/test" "test_expand_bz2")
else()
  add_test(bsdcat_test_expand_bz2 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(bsdcat_test_expand_gz "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcat_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcat.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cat/test" "test_expand_gz")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(bsdcat_test_expand_gz "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcat_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcat.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cat/test" "test_expand_gz")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(bsdcat_test_expand_gz "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcat_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcat.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cat/test" "test_expand_gz")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(bsdcat_test_expand_gz "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcat_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcat.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cat/test" "test_expand_gz")
else()
  add_test(bsdcat_test_expand_gz NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(bsdcat_test_expand_lz4 "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcat_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcat.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cat/test" "test_expand_lz4")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(bsdcat_test_expand_lz4 "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcat_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcat.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cat/test" "test_expand_lz4")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(bsdcat_test_expand_lz4 "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcat_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcat.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cat/test" "test_expand_lz4")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(bsdcat_test_expand_lz4 "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcat_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcat.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cat/test" "test_expand_lz4")
else()
  add_test(bsdcat_test_expand_lz4 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(bsdcat_test_expand_mixed "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcat_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcat.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cat/test" "test_expand_mixed")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(bsdcat_test_expand_mixed "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcat_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcat.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cat/test" "test_expand_mixed")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(bsdcat_test_expand_mixed "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcat_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcat.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cat/test" "test_expand_mixed")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(bsdcat_test_expand_mixed "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcat_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcat.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cat/test" "test_expand_mixed")
else()
  add_test(bsdcat_test_expand_mixed NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(bsdcat_test_expand_plain "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcat_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcat.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cat/test" "test_expand_plain")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(bsdcat_test_expand_plain "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcat_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcat.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cat/test" "test_expand_plain")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(bsdcat_test_expand_plain "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcat_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcat.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cat/test" "test_expand_plain")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(bsdcat_test_expand_plain "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcat_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcat.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cat/test" "test_expand_plain")
else()
  add_test(bsdcat_test_expand_plain NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(bsdcat_test_expand_xz "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcat_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcat.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cat/test" "test_expand_xz")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(bsdcat_test_expand_xz "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcat_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcat.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cat/test" "test_expand_xz")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(bsdcat_test_expand_xz "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcat_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcat.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cat/test" "test_expand_xz")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(bsdcat_test_expand_xz "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcat_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcat.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cat/test" "test_expand_xz")
else()
  add_test(bsdcat_test_expand_xz NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(bsdcat_test_expand_zstd "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcat_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcat.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cat/test" "test_expand_zstd")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(bsdcat_test_expand_zstd "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcat_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcat.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cat/test" "test_expand_zstd")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(bsdcat_test_expand_zstd "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcat_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcat.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cat/test" "test_expand_zstd")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(bsdcat_test_expand_zstd "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcat_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcat.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cat/test" "test_expand_zstd")
else()
  add_test(bsdcat_test_expand_zstd NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(bsdcat_test_help "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcat_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcat.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cat/test" "test_help")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(bsdcat_test_help "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcat_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcat.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cat/test" "test_help")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(bsdcat_test_help "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcat_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcat.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cat/test" "test_help")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(bsdcat_test_help "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcat_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcat.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cat/test" "test_help")
else()
  add_test(bsdcat_test_help NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(bsdcat_test_stdin "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcat_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcat.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cat/test" "test_stdin")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(bsdcat_test_stdin "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcat_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcat.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cat/test" "test_stdin")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(bsdcat_test_stdin "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcat_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcat.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cat/test" "test_stdin")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(bsdcat_test_stdin "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcat_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcat.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cat/test" "test_stdin")
else()
  add_test(bsdcat_test_stdin NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(bsdcat_test_version "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcat_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcat.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cat/test" "test_version")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(bsdcat_test_version "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcat_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcat.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cat/test" "test_version")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(bsdcat_test_version "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcat_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcat.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cat/test" "test_version")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(bsdcat_test_version "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcat_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcat.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cat/test" "test_version")
else()
  add_test(bsdcat_test_version NOT_AVAILABLE)
endif()
