# CMake generated Testfile for 
# Source directory: C:/Users/preet/Desktop/pe-sieve/osquery-plgx-extension/osquery/tools/tests
# Build directory: C:/Users/preet/Desktop/pe-sieve/osquery-plgx-extension/osquery/build/windows10/tools/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(python_test_osqueryi "C:/Python27/python.exe" "C:/Users/preet/Desktop/pe-sieve/osquery-plgx-extension/osquery/tools/tests/test_osqueryi.py" "--verbose" "--build" "C:/Users/preet/Desktop/pe-sieve/osquery-plgx-extension/osquery/build/windows10")
  set_tests_properties(python_test_osqueryi PROPERTIES  WORKING_DIRECTORY "C:/Users/preet/Desktop/pe-sieve/osquery-plgx-extension/osquery/tools/tests/")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(python_test_osqueryi "C:/Python27/python.exe" "C:/Users/preet/Desktop/pe-sieve/osquery-plgx-extension/osquery/tools/tests/test_osqueryi.py" "--verbose" "--build" "C:/Users/preet/Desktop/pe-sieve/osquery-plgx-extension/osquery/build/windows10")
  set_tests_properties(python_test_osqueryi PROPERTIES  WORKING_DIRECTORY "C:/Users/preet/Desktop/pe-sieve/osquery-plgx-extension/osquery/tools/tests/")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(python_test_osqueryi "C:/Python27/python.exe" "C:/Users/preet/Desktop/pe-sieve/osquery-plgx-extension/osquery/tools/tests/test_osqueryi.py" "--verbose" "--build" "C:/Users/preet/Desktop/pe-sieve/osquery-plgx-extension/osquery/build/windows10")
  set_tests_properties(python_test_osqueryi PROPERTIES  WORKING_DIRECTORY "C:/Users/preet/Desktop/pe-sieve/osquery-plgx-extension/osquery/tools/tests/")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(python_test_osqueryi "C:/Python27/python.exe" "C:/Users/preet/Desktop/pe-sieve/osquery-plgx-extension/osquery/tools/tests/test_osqueryi.py" "--verbose" "--build" "C:/Users/preet/Desktop/pe-sieve/osquery-plgx-extension/osquery/build/windows10")
  set_tests_properties(python_test_osqueryi PROPERTIES  WORKING_DIRECTORY "C:/Users/preet/Desktop/pe-sieve/osquery-plgx-extension/osquery/tools/tests/")
else()
  add_test(python_test_osqueryi NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(python_test_osqueryd "C:/Python27/python.exe" "C:/Users/preet/Desktop/pe-sieve/osquery-plgx-extension/osquery/tools/tests/test_osqueryd.py" "--verbose" "--build" "C:/Users/preet/Desktop/pe-sieve/osquery-plgx-extension/osquery/build/windows10")
  set_tests_properties(python_test_osqueryd PROPERTIES  WORKING_DIRECTORY "C:/Users/preet/Desktop/pe-sieve/osquery-plgx-extension/osquery/tools/tests/")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(python_test_osqueryd "C:/Python27/python.exe" "C:/Users/preet/Desktop/pe-sieve/osquery-plgx-extension/osquery/tools/tests/test_osqueryd.py" "--verbose" "--build" "C:/Users/preet/Desktop/pe-sieve/osquery-plgx-extension/osquery/build/windows10")
  set_tests_properties(python_test_osqueryd PROPERTIES  WORKING_DIRECTORY "C:/Users/preet/Desktop/pe-sieve/osquery-plgx-extension/osquery/tools/tests/")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(python_test_osqueryd "C:/Python27/python.exe" "C:/Users/preet/Desktop/pe-sieve/osquery-plgx-extension/osquery/tools/tests/test_osqueryd.py" "--verbose" "--build" "C:/Users/preet/Desktop/pe-sieve/osquery-plgx-extension/osquery/build/windows10")
  set_tests_properties(python_test_osqueryd PROPERTIES  WORKING_DIRECTORY "C:/Users/preet/Desktop/pe-sieve/osquery-plgx-extension/osquery/tools/tests/")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(python_test_osqueryd "C:/Python27/python.exe" "C:/Users/preet/Desktop/pe-sieve/osquery-plgx-extension/osquery/tools/tests/test_osqueryd.py" "--verbose" "--build" "C:/Users/preet/Desktop/pe-sieve/osquery-plgx-extension/osquery/build/windows10")
  set_tests_properties(python_test_osqueryd PROPERTIES  WORKING_DIRECTORY "C:/Users/preet/Desktop/pe-sieve/osquery-plgx-extension/osquery/tools/tests/")
else()
  add_test(python_test_osqueryd NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(python_test_windows_service "C:/Python27/python.exe" "C:/Users/preet/Desktop/pe-sieve/osquery-plgx-extension/osquery/tools/tests/test_windows_service.py" "--verbose" "--build" "C:/Users/preet/Desktop/pe-sieve/osquery-plgx-extension/osquery/build/windows10")
  set_tests_properties(python_test_windows_service PROPERTIES  WORKING_DIRECTORY "C:/Users/preet/Desktop/pe-sieve/osquery-plgx-extension/osquery/tools/tests/")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(python_test_windows_service "C:/Python27/python.exe" "C:/Users/preet/Desktop/pe-sieve/osquery-plgx-extension/osquery/tools/tests/test_windows_service.py" "--verbose" "--build" "C:/Users/preet/Desktop/pe-sieve/osquery-plgx-extension/osquery/build/windows10")
  set_tests_properties(python_test_windows_service PROPERTIES  WORKING_DIRECTORY "C:/Users/preet/Desktop/pe-sieve/osquery-plgx-extension/osquery/tools/tests/")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(python_test_windows_service "C:/Python27/python.exe" "C:/Users/preet/Desktop/pe-sieve/osquery-plgx-extension/osquery/tools/tests/test_windows_service.py" "--verbose" "--build" "C:/Users/preet/Desktop/pe-sieve/osquery-plgx-extension/osquery/build/windows10")
  set_tests_properties(python_test_windows_service PROPERTIES  WORKING_DIRECTORY "C:/Users/preet/Desktop/pe-sieve/osquery-plgx-extension/osquery/tools/tests/")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(python_test_windows_service "C:/Python27/python.exe" "C:/Users/preet/Desktop/pe-sieve/osquery-plgx-extension/osquery/tools/tests/test_windows_service.py" "--verbose" "--build" "C:/Users/preet/Desktop/pe-sieve/osquery-plgx-extension/osquery/build/windows10")
  set_tests_properties(python_test_windows_service PROPERTIES  WORKING_DIRECTORY "C:/Users/preet/Desktop/pe-sieve/osquery-plgx-extension/osquery/tools/tests/")
else()
  add_test(python_test_windows_service NOT_AVAILABLE)
endif()
