# CMake generated Testfile for 
# Source directory: C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test
# Build directory: C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(bsdcpio_test_0 "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_0")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(bsdcpio_test_0 "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_0")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(bsdcpio_test_0 "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_0")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(bsdcpio_test_0 "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_0")
else()
  add_test(bsdcpio_test_0 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(bsdcpio_test_basic "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_basic")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(bsdcpio_test_basic "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_basic")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(bsdcpio_test_basic "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_basic")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(bsdcpio_test_basic "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_basic")
else()
  add_test(bsdcpio_test_basic NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(bsdcpio_test_cmdline "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_cmdline")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(bsdcpio_test_cmdline "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_cmdline")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(bsdcpio_test_cmdline "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_cmdline")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(bsdcpio_test_cmdline "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_cmdline")
else()
  add_test(bsdcpio_test_cmdline NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(bsdcpio_test_format_newc "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_format_newc")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(bsdcpio_test_format_newc "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_format_newc")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(bsdcpio_test_format_newc "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_format_newc")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(bsdcpio_test_format_newc "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_format_newc")
else()
  add_test(bsdcpio_test_format_newc NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(bsdcpio_test_gcpio_compat "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_gcpio_compat")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(bsdcpio_test_gcpio_compat "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_gcpio_compat")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(bsdcpio_test_gcpio_compat "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_gcpio_compat")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(bsdcpio_test_gcpio_compat "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_gcpio_compat")
else()
  add_test(bsdcpio_test_gcpio_compat NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(bsdcpio_test_missing_file "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_missing_file")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(bsdcpio_test_missing_file "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_missing_file")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(bsdcpio_test_missing_file "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_missing_file")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(bsdcpio_test_missing_file "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_missing_file")
else()
  add_test(bsdcpio_test_missing_file NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(bsdcpio_test_option_0 "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_0")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(bsdcpio_test_option_0 "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_0")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(bsdcpio_test_option_0 "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_0")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(bsdcpio_test_option_0 "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_0")
else()
  add_test(bsdcpio_test_option_0 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(bsdcpio_test_option_B_upper "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_B_upper")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(bsdcpio_test_option_B_upper "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_B_upper")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(bsdcpio_test_option_B_upper "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_B_upper")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(bsdcpio_test_option_B_upper "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_B_upper")
else()
  add_test(bsdcpio_test_option_B_upper NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(bsdcpio_test_option_C_upper "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_C_upper")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(bsdcpio_test_option_C_upper "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_C_upper")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(bsdcpio_test_option_C_upper "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_C_upper")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(bsdcpio_test_option_C_upper "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_C_upper")
else()
  add_test(bsdcpio_test_option_C_upper NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(bsdcpio_test_option_J_upper "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_J_upper")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(bsdcpio_test_option_J_upper "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_J_upper")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(bsdcpio_test_option_J_upper "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_J_upper")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(bsdcpio_test_option_J_upper "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_J_upper")
else()
  add_test(bsdcpio_test_option_J_upper NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(bsdcpio_test_option_L_upper "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_L_upper")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(bsdcpio_test_option_L_upper "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_L_upper")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(bsdcpio_test_option_L_upper "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_L_upper")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(bsdcpio_test_option_L_upper "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_L_upper")
else()
  add_test(bsdcpio_test_option_L_upper NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(bsdcpio_test_option_Z_upper "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_Z_upper")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(bsdcpio_test_option_Z_upper "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_Z_upper")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(bsdcpio_test_option_Z_upper "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_Z_upper")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(bsdcpio_test_option_Z_upper "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_Z_upper")
else()
  add_test(bsdcpio_test_option_Z_upper NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(bsdcpio_test_option_a "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_a")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(bsdcpio_test_option_a "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_a")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(bsdcpio_test_option_a "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_a")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(bsdcpio_test_option_a "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_a")
else()
  add_test(bsdcpio_test_option_a NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(bsdcpio_test_option_b64encode "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_b64encode")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(bsdcpio_test_option_b64encode "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_b64encode")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(bsdcpio_test_option_b64encode "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_b64encode")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(bsdcpio_test_option_b64encode "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_b64encode")
else()
  add_test(bsdcpio_test_option_b64encode NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(bsdcpio_test_option_c "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_c")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(bsdcpio_test_option_c "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_c")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(bsdcpio_test_option_c "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_c")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(bsdcpio_test_option_c "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_c")
else()
  add_test(bsdcpio_test_option_c NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(bsdcpio_test_option_d "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_d")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(bsdcpio_test_option_d "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_d")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(bsdcpio_test_option_d "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_d")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(bsdcpio_test_option_d "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_d")
else()
  add_test(bsdcpio_test_option_d NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(bsdcpio_test_option_f "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_f")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(bsdcpio_test_option_f "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_f")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(bsdcpio_test_option_f "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_f")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(bsdcpio_test_option_f "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_f")
else()
  add_test(bsdcpio_test_option_f NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(bsdcpio_test_option_grzip "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_grzip")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(bsdcpio_test_option_grzip "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_grzip")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(bsdcpio_test_option_grzip "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_grzip")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(bsdcpio_test_option_grzip "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_grzip")
else()
  add_test(bsdcpio_test_option_grzip NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(bsdcpio_test_option_help "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_help")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(bsdcpio_test_option_help "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_help")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(bsdcpio_test_option_help "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_help")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(bsdcpio_test_option_help "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_help")
else()
  add_test(bsdcpio_test_option_help NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(bsdcpio_test_option_l "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_l")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(bsdcpio_test_option_l "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_l")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(bsdcpio_test_option_l "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_l")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(bsdcpio_test_option_l "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_l")
else()
  add_test(bsdcpio_test_option_l NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(bsdcpio_test_option_lrzip "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_lrzip")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(bsdcpio_test_option_lrzip "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_lrzip")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(bsdcpio_test_option_lrzip "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_lrzip")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(bsdcpio_test_option_lrzip "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_lrzip")
else()
  add_test(bsdcpio_test_option_lrzip NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(bsdcpio_test_option_lz4 "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_lz4")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(bsdcpio_test_option_lz4 "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_lz4")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(bsdcpio_test_option_lz4 "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_lz4")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(bsdcpio_test_option_lz4 "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_lz4")
else()
  add_test(bsdcpio_test_option_lz4 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(bsdcpio_test_option_lzma "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_lzma")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(bsdcpio_test_option_lzma "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_lzma")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(bsdcpio_test_option_lzma "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_lzma")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(bsdcpio_test_option_lzma "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_lzma")
else()
  add_test(bsdcpio_test_option_lzma NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(bsdcpio_test_option_lzop "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_lzop")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(bsdcpio_test_option_lzop "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_lzop")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(bsdcpio_test_option_lzop "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_lzop")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(bsdcpio_test_option_lzop "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_lzop")
else()
  add_test(bsdcpio_test_option_lzop NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(bsdcpio_test_option_m "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_m")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(bsdcpio_test_option_m "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_m")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(bsdcpio_test_option_m "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_m")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(bsdcpio_test_option_m "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_m")
else()
  add_test(bsdcpio_test_option_m NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(bsdcpio_test_option_passphrase "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_passphrase")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(bsdcpio_test_option_passphrase "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_passphrase")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(bsdcpio_test_option_passphrase "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_passphrase")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(bsdcpio_test_option_passphrase "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_passphrase")
else()
  add_test(bsdcpio_test_option_passphrase NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(bsdcpio_test_option_t "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_t")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(bsdcpio_test_option_t "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_t")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(bsdcpio_test_option_t "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_t")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(bsdcpio_test_option_t "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_t")
else()
  add_test(bsdcpio_test_option_t NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(bsdcpio_test_option_u "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_u")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(bsdcpio_test_option_u "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_u")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(bsdcpio_test_option_u "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_u")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(bsdcpio_test_option_u "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_u")
else()
  add_test(bsdcpio_test_option_u NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(bsdcpio_test_option_uuencode "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_uuencode")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(bsdcpio_test_option_uuencode "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_uuencode")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(bsdcpio_test_option_uuencode "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_uuencode")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(bsdcpio_test_option_uuencode "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_uuencode")
else()
  add_test(bsdcpio_test_option_uuencode NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(bsdcpio_test_option_version "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_version")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(bsdcpio_test_option_version "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_version")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(bsdcpio_test_option_version "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_version")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(bsdcpio_test_option_version "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_version")
else()
  add_test(bsdcpio_test_option_version NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(bsdcpio_test_option_xz "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_xz")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(bsdcpio_test_option_xz "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_xz")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(bsdcpio_test_option_xz "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_xz")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(bsdcpio_test_option_xz "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_xz")
else()
  add_test(bsdcpio_test_option_xz NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(bsdcpio_test_option_y "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_y")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(bsdcpio_test_option_y "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_y")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(bsdcpio_test_option_y "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_y")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(bsdcpio_test_option_y "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_y")
else()
  add_test(bsdcpio_test_option_y NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(bsdcpio_test_option_z "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_z")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(bsdcpio_test_option_z "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_z")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(bsdcpio_test_option_z "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_z")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(bsdcpio_test_option_z "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_z")
else()
  add_test(bsdcpio_test_option_z NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(bsdcpio_test_option_zstd "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_zstd")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(bsdcpio_test_option_zstd "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_zstd")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(bsdcpio_test_option_zstd "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_zstd")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(bsdcpio_test_option_zstd "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_option_zstd")
else()
  add_test(bsdcpio_test_option_zstd NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(bsdcpio_test_owner_parse "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_owner_parse")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(bsdcpio_test_owner_parse "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_owner_parse")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(bsdcpio_test_owner_parse "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_owner_parse")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(bsdcpio_test_owner_parse "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_owner_parse")
else()
  add_test(bsdcpio_test_owner_parse NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(bsdcpio_test_passthrough_dotdot "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_passthrough_dotdot")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(bsdcpio_test_passthrough_dotdot "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_passthrough_dotdot")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(bsdcpio_test_passthrough_dotdot "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_passthrough_dotdot")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(bsdcpio_test_passthrough_dotdot "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_passthrough_dotdot")
else()
  add_test(bsdcpio_test_passthrough_dotdot NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(bsdcpio_test_passthrough_reverse "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Debug/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_passthrough_reverse")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(bsdcpio_test_passthrough_reverse "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/Release/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_passthrough_reverse")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(bsdcpio_test_passthrough_reverse "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/MinSizeRel/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_passthrough_reverse")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(bsdcpio_test_passthrough_reverse "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcpio_test.exe" "-vv" "-p" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/bin/RelWithDebInfo/bsdcpio.exe" "-r" "C:/Users/preet/Desktop/libarchive-3.3.3/libarchive-3.3.3/cpio/test" "test_passthrough_reverse")
else()
  add_test(bsdcpio_test_passthrough_reverse NOT_AVAILABLE)
endif()
